[parity]
base_path = "$HOME/.ducatusx"
chain = "$HOME/.ducatusx/chain.json"
db_path = "$HOME/ducatusx/.ducatusx/chains"
keys_path = "$HOME/ducatusx/.ducatusx/keys"
identity = ""
light = false
[network]
allow_ips = "public"
port = 30301
[rpc]
interface = "all"
cors = ["all"]
port = 8546
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "pubsub"]
[websockets]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "pubsub"]
port = 8456
interface = "all"
[footprint]
db_compaction = "hdd"

[ipc]
disable = false

[misc]
logging = "own_tx=trace"
log_file = "$HOME/ducatusx/.ducatusx/debug.log"
color = true
